import express from 'express';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import authRoutes from './routes/authRoutes.js';
import transactionRoutes from './routes/transactionRoutes.js';
import budgetRoutes from './routes/budgetRoutes.js';
import dashboardRoutes from './routes/dashboardRoutes.js';
import preferenceRoutes from './routes/preferenceRoutes.js';
import categoryRoutes from './routes/categoryRoutes.js';
import recurringTransactionRoutes from './routes/recurringTransactionRoutes.js';
import { errorHandler, notFoundHandler } from './middleware/errorHandler.js';
import { requireUserContext } from './middleware/userContext.js';
import { env } from './config/env.js';

const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: env.clientOrigin, credentials: true, methods: ['GET', 'POST', 'PATCH', 'DELETE'] }));
app.use(express.json({ limit: '100kb' }));
app.use(cookieParser());
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 500, standardHeaders: 'draft-7', legacyHeaders: false }));
app.get('/health', (req, res) => res.json({ success: true, data: { status: 'ok' } }));
app.use('/api/auth', authRoutes);
app.use('/api', requireUserContext);
app.use('/api/transactions', transactionRoutes);
app.use('/api/budgets', budgetRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/preferences', preferenceRoutes);
app.use('/api/categories', categoryRoutes);
app.use('/api/recurring-transactions', recurringTransactionRoutes);
app.use(notFoundHandler);
app.use(errorHandler);
export default app;
